export const ADD_TO_CART = "ADD_TO_CART"
export const SET_TOTAL = "SET_TOTAL"
export const SUB_TOTAL = "SUB_TOTAL"
export const REMOVE_CART = "REMOVE_CART"

export const SET_GROCERY = "SET_GROCERY"
export const SELECTED_GROCERY = "SELECTED_GROCERY"

export const SET_MOBILE = "SET_MOBILE"
export const SELECTED_MOBILE = "SELECTED_MOBILE"

export const SET_FASHION = "SET_FASHION"
export const SELECTED_FASHION = "SELECTED_FASHION"

export const SET_USERS = "SET_USERS"
export const SELECTED_USERS = "SELECTED_USERS"

export const SET_CATEGORY = "SET_CATEGORY"

export const SET_ADDRESS = "SET_ADDRESS"

export const ADD_COUNT = "ADD_COUNT"
export const SUB_COUNT = "SUB_COUNT"

export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE"